version: '3.3'
services:
  db:
    build: ./postgres_build
    image: veronica_postgresql:1.0
    restart: always
    volumes:
      - ./postgres_build/postgresql.conf:/etc/postgresql/postgresql.conf
      - veronica-db-data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: change-password
      POSTGRES_DB: veronica-db
      PGDATA: /var/lib/postgresql/data/pgdata
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      front:
        ipv4_address: 172.70.0.2
  maven:
    build: .
    image: veronica_maven:1.0
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      DEPLOY: development
      POSTGRES_PASSWORD: change-password
      POSTGRES_DB: veronica-db
    networks:
      front:
        ipv4_address: 172.70.0.3
networks:
  front:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.70.0.0/28
volumes:
  veronica-db-data: